### ISSUE TITLE
Screenshots of unpolished stuff that need to be polished 

### ISSUE THREAD

**Issue by legendiguess** [nightblade9/eman-quest#1]
![unpolished_12](https://user-images.githubusercontent.com/40376451/55277801-00469880-5326-11e9-8995-99b698863187.PNG)
![unpolished_1](https://user-images.githubusercontent.com/40376451/55277802-00469880-5326-11e9-8223-121e63b75a67.PNG)
![unpolished_2](https://user-images.githubusercontent.com/40376451/55277803-00469880-5326-11e9-9817-3c4e824484e3.PNG)
![unpolished_3](https://user-images.githubusercontent.com/40376451/55277804-00df2f00-5326-11e9-8e7f-05d8bce3396f.PNG)
![unpolished_4](https://user-images.githubusercontent.com/40376451/55277805-00df2f00-5326-11e9-87bf-08ba25b3afd6.PNG)
![unpolished_6](https://user-images.githubusercontent.com/40376451/55277807-00df2f00-5326-11e9-8f6b-67db72b757b0.PNG)
![unpolished_7](https://user-images.githubusercontent.com/40376451/55277808-00df2f00-5326-11e9-8507-d8ea51a9d776.PNG)
![unpolished_8](https://user-images.githubusercontent.com/40376451/55277809-0177c580-5326-11e9-8aa1-ad8db10bd430.PNG)
Here enemy and hero sprites, i think, should be on same Y-axis. Also enemy and hero health bar should be on same Y-axis:
![unpolished_9](https://user-images.githubusercontent.com/40376451/55277810-0177c580-5326-11e9-9ee0-264a27b33052.PNG)
I think it's wrong tiles:
![unpolished_10](https://user-images.githubusercontent.com/40376451/55277811-0177c580-5326-11e9-9517-ec27f266e03b.PNG)
Some wierd with fullscreen mode:
![unpolished_11](https://user-images.githubusercontent.com/40376451/55277812-0177c580-5326-11e9-9664-680d6110e909.PNG)

**Comment by nightblade9** [comment]
Clarification on one of the points: there are three tiles that form an exit from a map, but only stepping on the middle one actually triggers a warp.

**Comment by nightblade9** [comment]
I've done everything I'm going to fix. To be clear, I fixed:

3) Player can walk on top of Baba
4) Player can walk on top of Hamza
5) Player can walk on stairs handrail
6) Player can walk on top of the bed
8) Player walks on top of ceiling tiles in desert dungeon in narrow corridors
9) Player sprites/text/health not aligned with monster in battles
10) Desert battle-back tiles are wrong on the bottom

What I didn't fix:

1) Player can walk on top of chests (this is on purpose so I can more easily spawn them, and not block important hallways/cooridors/etc.) - alternate solution would be to block with them, and make them disappear after opening. Worth it?

2) River cave exit tiles don't autotile nicely - seems like a Godot bug, can't upgrade to be 100% sure
7) Player can walk off of overworld (that's going away soon)
11) Full-screen mode (I have a separate work-item for this)

Thanks man, appreciate the help - let me know if 1) is worth fixing or not.
